name = "jace-memory-hub"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
API_KEY = "eba4c2552f5d52f8ec1fb056c8216c7bd1d04983d37c49dfd8ba4395ac4273e9"

[[d1_databases]]
binding = "DB"
database_name = "jace-memory-hub"
database_id = "01ab232e-c1ff-45b5-9608-fddbabfa8393"

[[vectorize]]
binding = "VECTORIZE"
index_name = "jace-mind-vectors"
